name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/var/www/html/apihackr"

    - name: Set permissions
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass  # Installer sshpass
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        
        sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          sudo chown -R www-data:www-data /var/www/html/apihackr
          sudo chmod -R 775 /var/www/html/apihackr/storage
          sudo chmod -R 775 /var/www/html/apihackr/bootstrap/cache
          sudo find /var/www/html/apihackr -type f -exec chmod 644 {} \;
          sudo find /var/www/html/apihackr -type d -exec chmod 755 {} \;
        EOF

